

ACCOUNT_ADMIN = 0
ACCOUNT_BUSINESS = 1
ACCOUNT_DEVELOPER = 2
ACCOUNT_PRIVATE = 3
ACCOUNT_STAFF = 4
ACCOUNT_RECHARGE = 5
ACCOUNT_EXTRA = 6
ACCOUNT_VENDOR = 7
ACCOUNT_PARTNER = 8

ACCOUNT_TYPE = (
    (ACCOUNT_ADMIN, 'ADMIN'),
    (ACCOUNT_BUSINESS, 'BUSINESS'),
    (ACCOUNT_DEVELOPER, 'DEVELOPER'),
    (ACCOUNT_PRIVATE, 'PRIVATE'),
    (ACCOUNT_STAFF, 'STAFF'),
    (ACCOUNT_RECHARGE, 'RECHARGE'),
    (ACCOUNT_VENDOR, 'VENDOR'),
    (ACCOUNT_EXTRA, 'EXTRA'),
    (ACCOUNT_PARTNET, 'PARTNER'),
)
